from __future__ import annotations

import csv
from datetime import datetime
from pathlib import Path
from typing import Any

from yandex_scraper.api.models import OrganizationCard
from yandex_scraper.config import REVIEW_DYNAMICS_OUTPUT_DIR


CSV_ENCODING = "utf-8-sig"
CSV_DELIMITER = ";"
SUMMARY_FILENAME = "review_dynamics_summary.csv"

INT_COLUMNS = {
    "total_reviews_since_start",
    "days_with_reviews",
    "reviews_last_7_days",
    "reviews_last_30_days",
    "reviews_last_90_days",
    "reviews_previous_7_days",
    "reviews_previous_30_days",
    "reviews_previous_90_days",
    "growth_7d_abs",
    "growth_30d_abs",
    "growth_90d_abs",
    "positive_reviews_count",
    "neutral_reviews_count",
    "negative_reviews_count",
    "negative_reviews_last_30_days",
}

FLOAT_COLUMNS = {
    "growth_7d_pct",
    "growth_30d_pct",
    "growth_90d_pct",
    "avg_review_rating",
    "negative_share",
    "avg_rating_last_30_days",
    "avg_rating_previous_30_days",
    "rating_change_30d",
    "negative_share_last_30_days",
}


def load_review_dynamics_for_card(
    record: OrganizationCard,
    source_path: Path | None = None,
) -> tuple[dict[str, Any], dict[str, Any]] | None:
    """Return review dynamics summary row matching an organization card."""

    source_path = Path(source_path or default_review_dynamics_summary_path())
    rows = load_review_dynamics_rows(source_path)
    candidates = _organization_key_candidates(record)

    for row in rows:
        if _clean(row.get("organization_key")) in candidates:
            return _normalize_row(row), source_snapshot(source_path)

    title = _normalize_text(record.title)
    address = _normalize_text(record.full_address)
    for row in rows:
        if _normalize_text(row.get("organization_title")) != title:
            continue
        row_address = _normalize_text(row.get("address"))
        if row_address and (row_address in address or address in row_address):
            return _normalize_row(row), source_snapshot(source_path)

    return None


def load_review_dynamics_rows(source_path: Path) -> list[dict[str, str]]:
    """Read review dynamics summary CSV generated by the analytics module."""

    if not source_path.exists():
        raise FileNotFoundError(f"Review dynamics summary not found: {source_path}")

    with source_path.open("r", encoding=CSV_ENCODING, newline="") as file:
        reader = csv.DictReader(file, delimiter=CSV_DELIMITER)
        return [dict(row) for row in reader]


def source_snapshot(source_path: Path | None = None) -> dict[str, Any]:
    path = Path(source_path or default_review_dynamics_summary_path())
    if not path.exists():
        return {
            "path": str(path),
            "exists": False,
            "sizeBytes": 0,
            "modifiedAt": None,
        }

    stat = path.stat()
    return {
        "path": str(path),
        "exists": True,
        "sizeBytes": stat.st_size,
        "modifiedAt": datetime.fromtimestamp(stat.st_mtime).astimezone().isoformat(timespec="seconds"),
    }


def default_review_dynamics_summary_path() -> Path:
    return REVIEW_DYNAMICS_OUTPUT_DIR / SUMMARY_FILENAME


def _organization_key_candidates(record: OrganizationCard) -> set[str]:
    return {
        candidate
        for candidate in (
            _clean(record.id),
            _clean(record.yandex_id),
            _clean(record.permalink),
        )
        if candidate
    }


def _normalize_row(row: dict[str, str]) -> dict[str, Any]:
    normalized: dict[str, Any] = {}
    for key, value in row.items():
        clean_key = _clean(key)
        if clean_key in INT_COLUMNS:
            normalized[clean_key] = _parse_int(value)
        elif clean_key in FLOAT_COLUMNS:
            normalized[clean_key] = _parse_float(value)
        else:
            normalized[clean_key] = _clean(value)
    return normalized


def _parse_int(value: object | None) -> int:
    text = _clean(value).replace(" ", "")
    if not text:
        return 0
    try:
        return int(text)
    except ValueError:
        try:
            return round(float(text.replace(",", ".")))
        except ValueError:
            return 0


def _parse_float(value: object | None) -> float | None:
    text = _clean(value).replace(" ", "")
    if not text:
        return None
    try:
        return float(text.replace(",", "."))
    except ValueError:
        return None


def _normalize_text(value: object | None) -> str:
    return " ".join(_clean(value).casefold().split())


def _clean(value: object | None) -> str:
    return str(value or "").strip()
